Repository AY2324S2-CS2103-F15-2/tp, pull requests merged in 2024-04, with the labels that each got.

#74 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/FilterActivityDiagram.puml
  docs/diagrams/FilterSequenceDiagram-Logic.puml
  docs/diagrams/FilterSequenceDiagram-Model.puml
  docs/diagrams/FilterState0.puml
  docs/diagrams/FilterState1.puml
  docs/images/FilterActivityDiagram.png
  docs/images/FilterSequenceDiagram-Logic.png
  docs/images/FilterSequenceDiagram-Model.png
  docs/images/FilterState0-FilteredList.png
  docs/images/FilterState1-FilteredList.png
Labels: documentation

#78 [gowthaman-01] Update delete command message from 'Person' to 'Student'.
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: bug

#79 [gowthaman-01] GUI enhancements
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement

#85 [gowthaman-01] Implement session note functionality
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Note.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/NoteWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/NoteWindow.css
  src/main/resources/view/NoteWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateDateTimeAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/person/NoteTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement

#94 Update landing page
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/GradeSubjectFilterPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: documentation

#101 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#164 Bug fix: Filter + Grade / Subject
  docs/UserGuide.md
  docs/images/FilterGradeA.png
  docs/images/filterGradeBPlusSubjectMaths.png
Labels: bug, enhancement

#165 Bug fix: History command + Misc.
  docs/UserGuide.md
  docs/images/commandHistory.png
  docs/images/commandHistory1.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: bug, enhancement

#168 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#170 Minor update to UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FilterSequenceDiagram-Logic.puml
  docs/images/FilterSequenceDiagram-Logic.png
Labels: documentation

#176 Fix note window width enlargement bug
  src/main/java/seedu/address/ui/NoteWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/NoteWindow.css
  src/main/resources/view/NoteWindow.fxml
Labels: bug

#175 Add note to UG and update help window message
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: bug

#173 Ensure note windows close when app closes
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#182 Add Note to Model UML diagram
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  src/main/java/seedu/address/MainApp.java
Labels: documentation
