Repository AY2324S2-CS2103-F15-2/tp, pull requests merged in 2024-03, with the labels that each got.

#6 Update Zheng Ting's Profile in AboutUs
  docs/AboutUs.md
  docs/images/al-zt.png
Labels: documentation

#8 Update payment functionality in User Guide
  docs/UserGuide.md
  docs/images/paymentJohnDoeFailure.png
  docs/images/paymentJohnDoeSuccess.png
Labels: documentation

#10 Changes to site-wide settings
  docs/AboutUs.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/index.md
Labels: documentation

#15 Update target user profile, value proposition and user stories in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#17 Update Haowen's profile in AboutUs
  docs/AboutUs.md
  docs/images/hwww23.png
Labels: documentation

#18 Update README.md
  README.md
  docs/images/Ui.png
Labels: documentation

#45 [gowthaman-01] Add gowthaman-01's profile picture
  docs/images/gowthaman-01.png
Labels: documentation

#49 Fix example Grade in ADD_COMMAND usage instructions
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: bug

#56 [gowthaman-01] Update Help Command
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: enhancement

#54 [gowthaman-01] Update Find command
  src/main/java/seedu/address/logic/Messages.java
Labels: bug

#58 Add attendance and payment
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Attendance.java
  src/main/java/seedu/address/model/person/Payment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AttendanceTest.java
  src/test/java/seedu/address/model/person/PaymentTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: enhancement

#57 [gowthaman-01] Update Edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: enhancement

#55 [gowthaman-01] Update List command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement

#59 Update UML in Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation

#61 Filter Student by Subject and Grade
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/person/Grade.java
  src/main/java/seedu/address/model/person/GradeSubjectFilterPredicate.java
  src/main/java/seedu/address/model/person/Subject.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/person/GradeSubjectFilterPredicateTest.java
Labels: enhancement

#67 Add calendar
  build.gradle
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ViewWindow.java
  src/main/resources/view/Calendar.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: enhancement
